### ISSUE TITLE
nvs_get_blob len fail: bleAddress NOT_FOUND

### ISSUE THREAD

**Issue by zvucetic** [uriyacovy/ESPHome_nuki_lock#12]
HI,

I'm using ESPHome version  2022.11.1 

I'm getting this issue (message) in the logs and Bluetooth is not working, not sure if the device is faulty or some other problem:

[04:00:08][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[04:00:09][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[04:00:09][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[04:00:10][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[04:00:10][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[04:00:11][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[04:00:11][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[04:00:12][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[04:00:12][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[04:00:13][E][Preferences.cpp:492] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND

[logs_nuki-bridge_upload (1).txt](https://github.com/uriyacovy/ESPHome_nuki_lock/files/10063137/logs_nuki-bridge_upload.1.txt)

**Comment by uriyacovy** [comment]
It looks like the module is not paired to Nuki. Did you follow the pairing sequence ([here](https://github.com/uriyacovy/ESPHome_nuki_lock#how-to-use))?

**Comment by zvucetic** [comment]
From what I managed to find out seems it's related to the ESP32 module. I ordered a new one, slightly different model, so I will report once it's comes.

**Comment by uriyacovy** [comment]
OK, please update if the problem is solved.

**Comment by zvucetic** [comment]
Hi, 
with the new ESP32 it works, so it was the HW issue. 
Thanks for the support.

**Comment by FelixAhrens** [comment]
@zvucetic I have the same problem, with 3 different boards, not sure if it's the HW. Which board works for you?

When I try to connect anyway, I get the following:

```
[ 70195][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
connectBle retry 0
pairNuki: connectBle success after 1050 ms
sendPlainMessage: connectBle success after 0 ms
E (79122) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (79122) task_wdt:  - loopTask (CPU 1)
E (79122) task_wdt: Tasks currently running:
E (79122) task_wdt: CPU 0: IDLE
E (79122) task_wdt: CPU 1: IDLE
E (79122) task_wdt: Aborting.

abort() was called at PC [...] on core 0


Backtrace: [...] |<-CORRUPTED
```
Can anyone help?

Thanks!

**Comment by uriyacovy** [comment]
Can you post your yaml?

**Comment by FelixAhrens** [comment]
```
esphome:
  name: nuki-bridge

  libraries:
  - Preferences
  - https://github.com/uriyacovy/NukiBleEsp32#dev

external_components:
  - source: github://uriyacovy/ESPHome_nuki_lock@dev

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0

lock:
  - platform: nuki_lock
    name: Nuki Lock
    is_connected: 
      name: "Nuki Connected"
    is_paired: 
      name: "Nuki Paired"      
    battery_critical:
      name: "Nuki Battery Critical"
    battery_level:
      name: "Nuki Battery Level"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: [...]

ota:
  password: [...]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nuki-Bridge Fallback Hotspot"
    password: [...]

captive_portal:
    
```
