### ISSUE TITLE
Build failed - esp_err.h: No such file or directory

### ISSUE THREAD

**Issue by flosch-dev** [uriyacovy/ESPHome_nuki_lock#28]
Hello, just got new Nuki 3 and wanted to use this nice implementation with ESPHome.
Unfortuantely the build with ESP Home within Home Assistant failed.
I tried to use ESPHome dev branch and also removing the arduino version as. 
I hope this is not a stupid problem on my side, I use other ESPhome devices already, but never with external libraries. Compiling the others work fine.

I'm running following version:
```
Home Assistant 2023.4.5
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest
```

ESPHome:
```
Current version: 2023.4.0
```
My ESPhome yaml looks like this:

```
esphome:
  name: nuki
  friendly_name: Nuki
  libraries:
  - Preferences
  - https://github.com/vinmenn/Crc16.git
  - https://github.com/uriyacovy/NukiBleEsp32

external_components:
  - source: github://uriyacovy/ESPHome_nuki_lock

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.3.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  password: "XXX"

wifi:
  ssid: XXX
  password: XXX

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nuki Fallback Hotspot"
    password: "XXX"

lock:
  # Required:
  - platform: nuki_lock
    name: Nuki Lock
    is_connected: 
      name: "Nuki Connected"
    is_paired: 
      name: "Nuki Paired"      
  # Optional:
    battery_critical:
      name: "Nuki Battery Critical"
    battery_level:
      name: "Nuki Battery Level"
    door_sensor:
      name: "Nuki Door Sensor"
    door_sensor_state:
      name: "Nuki Door Sensor State"

captive_portal:
    
```

When compiling, I get following errors:
```
INFO Reading configuration /config/esphome/nuki.yaml...
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Generating C++ source...
INFO Compiling app...
Processing nuki (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.3.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5

warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=False to SConscript calls.
Missing SConscript '/data/cache/platformio/packages/framework-arduinoespressif32@3.20003.220626/tools/platformio-build-esp32.py'
File "/data/cache/platformio/packages/framework-arduinoespressif32@3.20003.220626/tools/platformio-build.py", line 92, in <module>
Library Manager: Installing FS
Warning! Could not find the package with 'FS' requirements for your system 'linux_x86_64'
Library Manager: Installing Update
Warning! Could not find the package with 'Update' requirements for your system 'linux_x86_64'
Library Manager: Installing ESPmDNS
Warning! Could not find the package with 'ESPmDNS' requirements for your system 'linux_x86_64'
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- Preferences @ 2.1.0
|-- Crc16 @ 0.1.2+sha.719a7a1
|-- NukiBleEsp @ 2.0.0+sha.1de6290
|   |-- NimBLE-Arduino @ 1.4.1
|   |-- BleScanner @ 1.1.0+sha.575385f
|   |   |-- NimBLE-Arduino @ 1.4.1
|-- WiFi @ 1.2.7
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 1.1.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling /data/nuki/.pioenvs/nuki/src/esphome/components/api/api_connection.cpp.o
Compiling /data/nuki/.pioenvs/nuki/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/nuki/.pioenvs/nuki/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/nuki/.pioenvs/nuki/src/esphome/components/api/api_pb2_service.cpp.o
In file included from src/esphome/components/socket/socket.h:6,
                 from src/esphome/components/api/api_frame_helper.h:14,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome/components/api/api_connection.cpp:1:
src/esphome/components/socket/headers.h:127:10: fatal error: sys/ioctl.h: No such file or directory
 #include <sys/ioctl.h>
          ^~~~~~~~~~~~~
compilation terminated.
*** [/data/nuki/.pioenvs/nuki/src/esphome/components/api/api_connection.cpp.o] Error 1
In file included from src/esphome/components/api/proto.h:4,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_pb2.cpp:3:
src/esphome/core/log.h:14:10: fatal error: esp_err.h: No such file or directory

*****************************************************************
* Looking for esp_err.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_err.h"
* Web  > https://registry.platformio.org/search?q=header:esp_err.h
*
*****************************************************************

 #include <esp_err.h>
          ^~~~~~~~~~~
compilation terminated.
In file included from src/esphome/components/socket/socket.h:6,
                 from src/esphome/components/api/api_frame_helper.h:14,
                 from src/esphome/components/api/api_frame_helper.cpp:1:
src/esphome/components/socket/headers.h:127:10: fatal error: sys/ioctl.h: No such file or directory
 #include <sys/ioctl.h>
          ^~~~~~~~~~~~~
compilation terminated.
*** [/data/nuki/.pioenvs/nuki/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
*** [/data/nuki/.pioenvs/nuki/src/esphome/components/api/api_pb2.cpp.o] Error 1
In file included from src/esphome/components/api/proto.h:4,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_pb2_service.h:5,
                 from src/esphome/components/api/api_pb2_service.cpp:3:
src/esphome/core/log.h:14:10: fatal error: esp_err.h: No such file or directory

*****************************************************************
* Looking for esp_err.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_err.h"
* Web  > https://registry.platformio.org/search?q=header:esp_err.h
*
*****************************************************************

 #include <esp_err.h>
          ^~~~~~~~~~~
compilation terminated.
*** [/data/nuki/.pioenvs/nuki/src/esphome/components/api/api_pb2_service.cpp.o] Error 1
========================== [FAILED] Took 2.56 seconds ==========================
```
