### ISSUE TITLE
'ringbuf_type_t' has not been declared

### ISSUE THREAD

**Issue by zipposi** [uriyacovy/ESPHome_nuki_lock#35]
Hello!

I can't compile the code for ESP32 WROOM 32. I'm not very advanced user, so I would need some help with compiling.

Here's the code:

```
esphome:
  name: vhodna-vrata
#  friendly_name: Vhodna vrata

  libraries:
  - Preferences
  - https://github.com/vinmenn/Crc16.git
  - https://github.com/nkolban/ESP32_BLE_Arduino/
  - https://github.com/I-Connect/NukiBleEsp32

  
esp32:
  board: "nodemcu-32s"  # Or whatever other board you're using
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.3.0

substitutions:
  device_name: "Vrata"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2
    - ssid: !secret work_ssid
      password: !secret work_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

external_components:
  - source: github://uriyacovy/ESPHome_nuki_lock

lock:
  - platform: nuki_lock
    name: Nuki Lock
    is_connected: 
      name: "${device_name} Connected"
    is_paired: 
      name: "${device_name} Paired"      
  # Optional:
    battery_critical:
      name: "${device_name} Battery Critical"
    battery_level:
      name: "${device_name} Battery Level"
    door_sensor:
      name: "${device_name} Door Sensor"
    door_sensor_state:
      name: "${device_name} Door Sensor State"
```

Here's the log:

```
INFO ESPHome 2023.8.2
INFO Reading configuration /config/esphome/vhodna-vrata.yaml...
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Generating C++ source...
INFO Compiling app...
Processing vhodna-vrata (board: nodemcu-32s; framework: arduino; platform: platformio/espressif32@5.3.0)
--------------------------------------------------------------------------------
Removing unused dependencies...
Library Manager: Installing git+https://github.com/vinmenn/Crc16.git
INFO Installing git+https://github.com/vinmenn/Crc16.git
git version 2.30.2
Cloning into '/data/cache/platformio/cache/tmp/pkg-installing-z88257fe'...
Library Manager: Crc16@0.1.2+sha.719a7a1 has been installed!
INFO Crc16@0.1.2+sha.719a7a1 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- Preferences @ 2.0.0
|-- Crc16 @ 0.1.2+sha.719a7a1
|-- ESP32 BLE Arduino @ 1.0.1+sha.adc2aee
|-- NukiBleEsp @ 2.0.0+sha.707b327
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/api/api_connection.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/api/api_server.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/api/list_entities.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/api/proto.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/api/user_services.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/binary_sensor/automation.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/binary_sensor/filter.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/esp32/core.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/esp32/gpio.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/esp32/preferences.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/lock/lock.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/logger/logger.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/md5/md5.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/mdns/mdns_component.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/mdns/mdns_host.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/network/util.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/nuki_lock/nuki_lock.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/ota/ota_component.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/sensor/automation.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/sensor/filter.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/sensor/sensor.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/socket/socket.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/switch/automation.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/switch/switch.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/text_sensor/filter.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/text_sensor/text_sensor.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/wifi/wifi_component.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/application.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/color.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/component.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/component_iterator.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/controller.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/entity_base.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/helpers.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/log.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/scheduler.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/string_ref.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/time.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/esphome/core/util.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/src/main.cpp.o
Generating partitions /data/vhodna-vrata/.pioenvs/vhodna-vrata/partitions.bin
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/liba6d/AsyncTCP-esphome/AsyncTCP.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/lib080/Preferences/Preferences.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/lib947/Crc16/Crc16.cpp.o
Archiving /data/vhodna-vrata/.pioenvs/vhodna-vrata/lib080/libPreferences.a
Archiving /data/vhodna-vrata/.pioenvs/vhodna-vrata/liba6d/libAsyncTCP-esphome.a
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/libac4/ESP32 BLE Arduino/BLE2902.cpp.o
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/libac4/ESP32 BLE Arduino/BLE2904.cpp.o
Archiving /data/vhodna-vrata/.pioenvs/vhodna-vrata/lib947/libCrc16.a
Compiling /data/vhodna-vrata/.pioenvs/vhodna-vrata/libac4/ESP32 BLE Arduino/BLEAddress.cpp.o
In file included from /data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/BLECharacteristic.h:19,
                 from /data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/BLEDescriptor.h:14,
                 from /data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/BLE2902.h:13,
                 from /data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/BLE2902.cpp:15:
/data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/FreeRTOS.h:61:28: error: 'ringbuf_type_t' has not been declared
  Ringbuffer(size_t length, ringbuf_type_t type = RINGBUF_TYPE_NOSPLIT);
                            ^~~~~~~~~~~~~~
In file included from /data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/BLECharacteristic.h:19,
                 from /data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/BLEDescriptor.h:14,
                 from /data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/BLE2904.h:13,
                 from /data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/BLE2904.cpp:15:
/data/vhodna-vrata/.piolibdeps/vhodna-vrata/ESP32 BLE Arduino/src/FreeRTOS.h:61:28: error: 'ringbuf_type_t' has not been declared
  Ringbuffer(size_t length, ringbuf_type_t type = RINGBUF_TYPE_NOSPLIT);
                            ^~~~~~~~~~~~~~
*** [/data/vhodna-vrata/.pioenvs/vhodna-vrata/libac4/ESP32 BLE Arduino/BLE2902.cpp.o] Error 1
*** [/data/vhodna-vrata/.pioenvs/vhodna-vrata/libac4/ESP32 BLE Arduino/BLE2904.cpp.o] Error 1
========================= [FAILED] Took 86.52 seconds =========================
```
