### ISSUE TITLE
Activity log

### ISSUE THREAD

**Issue by szisso** [uriyacovy/ESPHome_nuki_lock#42]
Is there support of activity log?
I would like to get the name of the device that lock/unlock the door.
While searching the web I saw that authorizationName is the value that use by the Nukihub components but I couldn’t find documentation on the esphome version

**Comment by AzonInc** [comment]
Are you still looking for log support?
Would be nice to have someone testing the new feature.

**Comment by szisso** [comment]
Yes I am still need itShai Zisso‫ב-26 באוק׳ 2024, בשעה 21:59, ‏‏Flo ***@***.***> כתב/ה:‬﻿
Are you still looking for log support?
Would be nice to have someone testing the new feature.

**Comment by AzonInc** [comment]
Okay so lets give the auth-logs branch a shot.

```yaml
esphome:
  libraries:
  - Preferences
  - https://github.com/h2zero/NimBLE-Arduino#1.4.0
  - Crc16
  - https://github.com/uriyacovy/NukiBleEsp32

external_components:
  - source: github://AzonInc/ESPHome_nuki_lock@feature/auth-logs
```
