### ISSUE TITLE
Feature request: Open doors with door knobs is missing.

### ISSUE THREAD

**Issue by shiSHARK** [uriyacovy/ESPHome_nuki_lock#5]
The integration works great. 

But I'm missing the open door feature. Since my door is with a door knob and not with a handle on the outside I can't open the door from the outside. It will be great to add open functionality as a separate entity.

I really like that it allows me to unlock and lock the door without actually opening it. But there is need for open door button where the outside of the door is using a knob.

**Comment by uriyacovy** [comment]
Hi shiSHARK,
This is already implemented with HA open service. See here: https://github.com/uriyacovy/ESPHome_nuki_lock/issues/1
Let me know if this doesn't work for you.

**Comment by crixionz** [comment]
The issue here might be that HA's frontend doesn't show an open button (yet). 
I filed this [esphome issue #3495](https://github.com/esphome/issues/issues/3495) and they confirmed it's an issue of HA, not ESPHome.

@shiSHARK try this in [🔨Developer Tools → Services](https://my.home-assistant.io/redirect/developer_services/):
```yaml
service: lock.open
target:
  entity_id: lock.mynuki   (← or whatever your nuki's entity_id is in your HA) 
  ```
It should open your nuki door. 
If that works, you can use it in automations or scripts.
Or you could set up a button in ESPHome which you can then use in Lovelace:
```yaml
esphome: 
# ...
button:
  - platform: template
    name: "Nuki Open"
    on_press:
      - lock.open: mynuki

lock:
  - platform: nuki_lock
    id: mynuki
    # ...
```
