### ISSUE TITLE
opened on wrong repo

### ISSUE THREAD

**Issue by bunit17** [uriyacovy/ESPHome_nuki_lock#53]
Hi,

I am getting to following error when trying to install using the updated external_components options. I have followed the example template to set up the configrations.

```
src/esphome/components/esp32_ble_presense/esp32_ble_presense.cpp:9:10: fatal error: NimBLEDevice.h: No such file or directory

**********************************************************************
* Looking for NimBLEDevice.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:NimBLEDevice.h"
* Web  > https://registry.platformio.org/search?q=header:NimBLEDevice.h
*
**********************************************************************

 #include <NimBLEDevice.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/everything-presence-one-dea478/src/esphome/components/esp32_ble_presense/esp32_ble_presense.o] Error 1
========================= [FAILED] Took 15.88 seconds =========================
```
This is my set up
```
mqtt:
  broker: XXX
  username: XXXX
  password: XXXX
  discovery: true

# Adding external component to build:
external_components:
  source: github://formatBCE/ESP32_BLE_presense@main

# System time config - required for precise timestamps, used in integration:
time:
  - platform: homeassistant
    id: homeassistant_time

# Initializing it:
esp32_ble_presense:
  area: "living_room" # Replace this with your room name
  time_id: homeassistant_time

```
