### ISSUE TITLE
API disconnects every second (approx. since V 0.0.4)

### ISSUE THREAD

**Issue by Pe-MaKer** [uriyacovy/ESPHome_nuki_lock#66]
Every few days, my ESPHome-Nuki-Lock enters a state where the api conntection to HA becomes unstable.
This never occured on older versions of this outstanding integration.

See below the HA Core Logs and a screenshot of the ESP32 Log.

```
Logger: aioesphomeapi.connection
Quelle: runner.py:154
Erstmals aufgetreten: 10:09:34 (2015 Vorkommnisse)
Zuletzt protokolliert: 10:45:58

haustuer @ 10.0.2.3: Connection error occurred: Invalid protobuf message: type=HomeassistantServiceResponse data=b'\n\x0cesphome.nuki\x12\x14\n\x06action\x12\nDoorClosed\x12\x1d\n\x0fauthorizationId\x12\n4294967295\x12;\n\x11authorizationName\x12&\xfd\xdb${\xaa\xc8\xe4DN\xec@\n\xc4A\xe5&\x0f\xca%&\xf8a\xd8\xf09?\xd1\xc3,\x96\x06\xfe\xc2\xf2_+\x01\xc4\x12\x0e\n\x05index\x12\x0528210\x12\r\n\x07timeDay\x12\x0215\x12\x0e\n\x08timeHour\x12\x0211\x12\x0f\n\ntimeMinute\x12\x016\x12\x0f\n\ttimeMonth\x12\x0212\x12\x10\n\ntimeSecond\x12\x0243\x12\x10\n\x08timeYear\x12\x042024\x12\x12\n\x04type\x12\nDoorSensor(\x01': Error parsing message with type 'HomeassistantServiceResponse'
haustuer @ 10.0.2.3: Connection error occurred: Invalid protobuf message: type=TextSensorStateResponse data=b'\rF\x13j^\x12&\xfd\xdb${\xaa\xc8\xe4DN\xec@\n\xc4A\xe5&\x0f\xca%&\xf8a\xd8\xf09?\xd1\xc3,\x96\x06\xfe\xc2\xf2_+\x01\xc4': Error parsing message with type 'TextSensorStateResponse'
haustuer @ 10.0.2.3: Connection error occurred: Invalid protobuf message: type=HomeassistantServiceResponse data=b'\n\x0cesphome.nuki\x12\x14\n\x06action\x12\nDoorClosed\x12\x1d\n\x0fauthorizationId\x12\n4294967295\x123\n\x11authorizationName\x12\x1e\xfd\xdb${\xaa\xc8\xe4DN\xec@\n\xc4A\xe5&\x0f\xca%&\xf8a\xd8\xf09?\xd1\xc3=k\x12\x0e\n\x05index\x12\x0528210\x12\r\n\x07timeDay\x12\x0215\x12\x0e\n\x08timeHour\x12\x0211\x12\x0f\n\ntimeMinute\x12\x016\x12\x0f\n\ttimeMonth\x12\x0212\x12\x10\n\ntimeSecond\x12\x0243\x12\x10\n\x08timeYear\x12\x042024\x12\x12\n\x04type\x12\nDoorSensor(\x01': Error parsing message with type 'HomeassistantServiceResponse'
haustuer @ 10.0.2.3: Connection error occurred: Invalid protobuf message: type=TextSensorStateResponse data=b'\rF\x13j^\x12\x1e\xfd\xdb${\xaa\xc8\xe4DN\xec@\n\xc4A\xe5&\x0f\xca%&\xf8a\xd8\xf09?\xd1\xc3=k': Error parsing message with type 'TextSensorStateResponse'
```
![2024-12-16 10_23_25-Haustür](https://github.com/user-attachments/assets/c782d60e-4256-44f6-b40f-80a94f7d398b)

**Comment by AzonInc** [comment]
Hi,

Could you please try version 0.0.4 and confirm whether the issue starts with this version? There are no significant changes between 0.0.3 and 0.0.4, so it would be helpful to verify this.

Thanks

**Comment by Pe-MaKer** [comment]
@AzonInc I have no clue on how to use a specific version.
I need to clear the built files, I assume. But how can I compile using a previous version?

**Comment by uriyacovy** [comment]
Use the following:
```
external_components:
  - source: github://uriyacovy/ESPHome_nuki_lock@v0.0.4

```

**Comment by Pe-MaKer** [comment]
> Use the following:
> 
> ```
> external_components:
>   - source: github://uriyacovy/ESPHome_nuki_lock@v0.0.4
> ```

It's throwing a fatal error - even after commenting out the recent added sensor like nightmode and last_unlock_user:
```
Compiling .pioenvs/haustuer/src/esphome/components/nuki_lock/nuki_lock.cpp.o
In file included from src/esphome/components/nuki_lock/nuki_lock.cpp:3:
src/esphome/components/nuki_lock/nuki_lock.h:12:10: fatal error: NukiLock.h: No such file or directory

******************************************************************
* Looking for NukiLock.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:NukiLock.h"
* Web  > https://registry.platformio.org/search?q=header:NukiLock.h
*
******************************************************************

 #include "NukiLock.h"
          ^~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/haustuer/src/esphome/components/nuki_lock/nuki_lock.cpp.o] Error 1
========================= [FAILED] Took 25.96 seconds =========================```

**Comment by AzonInc** [comment]
Did u add the libraries block? It's still needed for versions < 0.0.5

```
esphome:
  libraries:
  - Preferences
  - https://github.com/vinmenn/Crc16.git
  - https://github.com/uriyacovy/NukiBleEsp32
```

**Comment by Pe-MaKer** [comment]
Thanks @AzonInc 
But I still get this.
![image](https://github.com/user-attachments/assets/e448102b-bc28-422a-a07a-feb83c97d25b)

Here is my code:
```
substitutions:
  display_name: haustuer

  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

# ------------------------------
# ------------------------------
esphome:
  name: ${display_name}
  friendly_name: Haustür


  libraries:
  - Preferences
  - https://github.com/vinmenn/Crc16.git
  - https://github.com/uriyacovy/NukiBleEsp32


external_components:
  - source: github://uriyacovy/ESPHome_nuki_lock@v0.0.4
  #- source: github://Pe-MaKer/ESPHome_nuki_lock@dev

esp32:
  board: "wemos_d1_mini32"
  framework:
    type: arduino
    version: 2.0.16
    platform_version: 6.7.0

wifi:
  networks:
  - ssid: ${wifi_ssid}
    password: ${wifi_password}
  - ssid: ${wifi_ssid2}
    password: ${wifi_password2}
  # Optional manual IP
  manual_ip:
    static_ip: 10.0.X.XX
    gateway: 10.0.0.1
    subnet: 255.0.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${display_name}_AP
    password: ${wifi_password}
    ap_timeout: 1min

captive_portal:

#bluetooth_proxy:
#  active: true

logger:
  level: DEBUG
api:

#ota:
#  password: "notwhatyouthink"
ota:
  - platform: esphome    
    password: !secret ota_password
    id: my_ota
safe_mode:


web_server:
  port: 80
  include_internal: true


number:
  - platform: template
    name: "Türöffner Delay"
    id: turoffner_delay
    optimistic: true
    min_value: 0      # Minimale Dauer des Delay in Sekunden
    max_value: 10000     # Maximale Dauer des Delay in Sekunden
    step: 250
    initial_value: 2000  # Default-Wert für den Delay beim Start
  - platform: template
    name: "Durchgangslicht Delay"
    id: durchgangslicht_delay
    optimistic: true
    min_value: 1      # Minimale Dauer des Delay in Sekunden
    max_value: 600     # Maximale Dauer des Delay in Sekunden
    step: 1
    initial_value: 120  # Default-Wert für den Delay beim Start


button:
  - platform: template
    name: "Türöffner"
    id: turoffner
    icon: "mdi:door-open"
    on_press:
      - if:
          condition: 
            lock.is_locked: nuki
          then:
            - lock.unlock: nuki
            - delay: 5s
            - switch.turn_on: oeffner
            - delay: !lambda "return id(turoffner_delay).state;"
            - switch.turn_off: oeffner

          else:
            - switch.turn_on: oeffner
            - delay: !lambda "return id(turoffner_delay).state;"
            #- delay: 2000ms
            - switch.turn_off: oeffner
  - platform: template
    name: "Durchgangslicht"
    id: durchgangslicht
    icon: "mdi:wall-sconce-flat"
    on_press:
      - output.turn_on: licht
      #- delay: 120000ms
      - delay: !lambda "return 1000 * id(durchgangslicht_delay).state;"
      - output.turn_off: licht

  - platform: restart
    name: "Restart haustuer"
  
switch:
  - platform: gpio
    id: oeffner
    pin: 16
    restore_mode: ALWAYS_OFF
    name: "Schnapper"
    icon: "mdi:gate"


output:
  - platform: gpio
    id: licht
    pin: 17    

    
light:
  - platform: binary
    name: "Licht"
    output: licht


lock:
  # Required:
  - platform: nuki_lock
    name: Nuki ESP
    id: nuki
    is_connected: 
      name: "Nuki ESP verbunden"
    is_paired: 
      name: "Nuki ESP gekoppelt"      

    battery_critical:
      name: "Nuki ESP Batterie kritisch"
    battery_level:
      name: "Nuki ESP Batteriestand"
    door_sensor:
      name: "Nuki ESP Türsensor"
    door_sensor_state:
      name: "Nuki ESP Türkontakt Zustand"
    unpair:
      name: "Nuki Unpair"
    pairing_mode:
      name: "Nuki Pairing Mode"



    on_pairing_mode_on_action:
      - lambda: ESP_LOGI("nuki_lock", "Pairing Mode aktiviert");
    on_pairing_mode_off_action:
      - lambda: ESP_LOGI("nuki_lock", "Pairing Mode deaktiviert");
    on_paired_action:
      - lambda: ESP_LOGI("nuki_lock", "Pairing erfolgreich");

```
