### ISSUE TITLE
Support for Smart Lock Ultra

### ISSUE THREAD

**Issue by B-Hartley** [uriyacovy/ESPHome_nuki_lock#67]
How practical is it for you to modify (or guide me how to modify) this to support Smart Lock Ultra?
Is there anything I can do to give you the info you would need?

Thanks

**Comment by AzonInc** [comment]
This component is based on the https://github.com/I-Connect/NukiBleEsp32 project so you should open an issue there I guess.

If it's supported by that project, it's possible to support it in this component as well.

**Comment by B-Hartley** [comment]
Thanks for replying.
I realised that my first error was probably not specifying the security pin to allow pairing to work.
Unfortunately I can't.
The Ultra requires a 6 digit pin and as the PIN field is a "number" it won't allow numbers that big.
It would need to be a text field.

I guess I'll have to fork and have an experiment changing it to a text field so I can put in a bigger number.

**Comment by AzonInc** [comment]
The docs of Nuki state that it's a uint16 which has a max of 65535 but thats as of 2020.
It could have changed now.

**Comment by B-Hartley** [comment]
![image](https://github.com/user-attachments/assets/2efb6dae-f118-4f7b-8060-e620d9b77bac)

Yes. It requires a 6 digit pin. So guess it's either a 32 or text.

**Comment by AzonInc** [comment]
We should open an issue in the other project for now so they add support for it.

**Comment by AzonInc** [comment]
If you're still down for testing the ultra version it's here: https://github.com/uriyacovy/ESPHome_nuki_lock/tree/ultra
This one also supports esp-idf which I would recommend in general.

Example config:
```yaml
external_components:
  - source: github://uriyacovy/ESPHome_nuki_lock@ultra

esp32:
  board: "esp32dev"
  framework:
    type: esp-idf

lock:
  # Required
  - platform: nuki_lock
    name: Nuki Lock
  # Optional: Settings
    pairing_mode_timeout: 300s
    event: "nuki"
    security_pin: 1234
  # Optional: Advanced Settings
    alternative_connect_mode: true
    pairing_as_app: false
    ultra_pairing_mode: false
    query_interval_config: 3600s
    query_interval_auth_data: 7200s

  # Optional: Binary Sensors
    is_connected:
      name: "Nuki Connected"
    is_paired:
      name: "Nuki Paired"
    battery_critical:
      name: "Nuki Battery Critical"
    door_sensor:
      name: "Nuki Door Sensor"
  # Optional: Sensors
    battery_level:
      name: "Nuki Battery Level"
    bt_signal_strength:
      name: "Bluetooth Signal Strength"
  # Optional: Text Sensors
    door_sensor_state:
      name: "Nuki Door Sensor: State"
    last_unlock_user:
      name: "Nuki Last Unlock User"
    last_lock_action:
      name: "Nuki Last Lock Action"
    last_lock_action_trigger:
      name: "Nuki Last Lock Action Trigger"
    pin_status:
      name: "Nuki Security Pin Status"
  # Optional: Number Inputs
    led_brightness:
      name: "Nuki LED Brightness"
    timezone_offset:
      name: "Nuki Timezone: Offset"
    lock_n_go_timeout:
      name: "Nuki LockNGo Timeout"
  # Optional: Switches
    pairing_mode:
      name: "Nuki Pairing Mode"
    auto_unlatch:
      name: "Nuki Auto unlatch"
    button_enabled:
      name: "Nuki Button: Locking operations"
    led_enabled:
      name: "Nuki LED Signal"
    night_mode_enabled:
      name: "Nuki Night Mode"
    night_mode_auto_lock_enabled:
      name: "Nuki Night Mode: Auto Lock"
    night_mode_auto_unlock_disabled:
      name: "Nuki Night Mode: Reject Auto Unlock"
    night_mode_immediate_lock_on_start_enabled:
      name: "Nuki Night Mode: Lock at Start Time"
    auto_lock_enabled:
      name: "Nuki Auto Lock"
    auto_unlock_disabled:
      name: "Nuki Auto Unlock: Disable"
    immediate_auto_lock_enabled:
      name: "Nuki Auto Lock: Immediately"
    auto_update_enabled:
      name: "Nuki Automatic Updates"
    single_lock_enabled:
      name: "Nuki Single Lock"
    dst_mode_enabled:
      name: "Nuki Daylight Saving Time"
    auto_battery_type_detection_enabled:
      name: "Nuki Automatic Battery Type Detection"
    slow_speed_during_night_mode_enabled:
      name: "Nuki Slow Speed During Night Mode"
  # Optional: Select Inputs
    single_buton_press_action:
      name: "Nuki Button: Single Press Action"
    double_buton_press_action:
      name: "Nuki Button: Double Press Action"
    fob_action_1:
      name: "Nuki Fob: Action 1"
    fob_action_2:
      name: "Nuki Fob: Action 2"
    fob_action_3:
      name: "Nuki Fob: Action 3"
    timezone:
      name: "Nuki Timezone"
    advertising_mode:
      name: "Nuki Advertising Mode"
    battery_type:
      name: "Nuki Battery Type"
    motor_speed:
      name: "Nuki Motor Speed"
  # Optional: Buttons
    unpair:
      name: "Nuki Unpair Device"
  # Optional: Callbacks
    on_pairing_mode_on_action:
      - lambda: ESP_LOGI("nuki_lock", "Pairing mode turned on");
    on_pairing_mode_off_action:
      - lambda: ESP_LOGI("nuki_lock", "Pairing mode turned off");
    on_paired_action:
      - lambda: ESP_LOGI("nuki_lock", "Paired sucessfuly");
```

**Comment by philipparndt** [comment]
I can confirm this is working with the Ultra Lock.
Maybe it is worth noting, that you need to enable Bluetooth pairing in the Nuki App to make this work (took me a while to figure this out). 

See description here: https://github.com/technyon/nuki_hub?tab=readme-ov-file#pairing-with-a-nuki-lock-ultra

**Comment by AzonInc** [comment]
That's cool.
Could you please provide some logs for idf when compile fails?

**Comment by AzonInc** [comment]
Did you set the pairing pin first?

**Comment by brotaxt** [comment]
Yes, in the device config under the lock: section

**Comment by brotaxt** [comment]
I've tried it once again, I keep getting the mentioned error message

```
[08:46:01][D][esp-idf:000]: E (72124) NukiBle: Error getting data from NVS
[08:46:01][D][esp-idf:000]: E (72622) NukiBle.Preferences: nvs_get_blob len fail: bleAddress NOT_FOUND
```

**Comment by mhier** [comment]
I don't really understand what's going wrong here. I rebased on the latest main (see https://github.com/mhier/ESPHome_nuki_lock/tree/ultra) but it did not help. I can easily pair the same hardware when using nuki_hub. The weird thing is that it uses the same version of NukiBle, and I don't really find any obvious difference how NukiBle is used (I saw the transmit power setting was missing, but it makes no difference either).

Any hint what could be wrong here? Maybe the build system? We have to use Arduino at the moment, as with IDF  different dependency version/fork is used...

**Comment by AzonInc** [comment]
I need a tester for the following config with Ultra / Go / 5th Gen Lock.

Please use this minimal config as is and set your wifi credentials as well as the pin.
```yaml
esphome:
  name: nuki-lock
  friendly_name: Nuki Lock
  on_boot:
    - lambda: |-
        esp_log_level_set("wifi", ESP_LOG_WARN);

esp32:
  variant:  ESP32S3
  framework:
    type: esp-idf
    log_level: INFO

logger:
  level: DEBUG

wifi:
  ssid: "YourSSID"
  password: "YourPassword"

psram:
  mode: octal
  speed: 80MHz

api:

external_components:
  - source: github://uriyacovy/ESPHome_nuki_lock@pairing-issue
    refresh: 10s

lock:
  - platform: nuki_lock
    name: Nuki Lock
    security_pin: 123456
    pairing_as_app: true
    is_connected:
      name: "Nuki Connected"
    is_paired:
      name: "Nuki Paired"
    pairing_mode:
      name: "Nuki Pairing Mode"
    unpair:
      name: "Nuki Unpair Device"
    on_pairing_mode_on_action:
      - lambda: ESP_LOGI("nuki_lock", "Pairing mode turned on");
    on_pairing_mode_off_action:
      - lambda: ESP_LOGI("nuki_lock", "Pairing mode turned off");
    on_paired_action:
      - lambda: ESP_LOGI("nuki_lock", "Paired sucessfuly");
```

Make sure "Bluetooth pairing" is enabled for the Nuki device by enabling this setting in the official Nuki App in "Settings" > "Features & Configuration" > "Button and LED".
