### ISSUE TITLE
ESP locks up after several hours

### ISSUE THREAD

**Issue by s00500** [uriyacovy/ESPHome_nuki_lock#76]
after an average of about 48h my esp usually becomes unresponsive until I reset it again ... I though for a long while that this might be related to the power supply but now I have a really stable one and it still happens...

Anyone else experiencing issues like these ?

**Comment by AzonInc** [comment]
Did you try disableing the events by setting event: none ?
That might free up some resources and disables code for gathering event logs as well as the Home Assistant API log streaming.

**Comment by s00500** [comment]
Hm yes, already running like that:

````
external_components:
  - source:
      type: git
      url: https://github.com/uriyacovy/ESPHome_nuki_lock
      ref: improve-memory-footprint
    components: [nuki_lock]

esp32:
  board: "esp32dev" # Or whatever other board you're using
  framework:
    type: arduino
    version: 2.0.16
    platform_version: 6.7.0

lock:
  # Required
  - platform: nuki_lock
    name: Main Lock
    # Optional: Settings
    pairing_mode_timeout: 300s
    event: "none"
    # Optional: Binary Sensors
````
